
# This is a http file which has requests that are sent to a web service given by fakestoreapi which in turn is connected to web server
# In other examples, like the eg - 1 of main.dart, we are building the webservice itself using app.py(flask) 
# This is just to demonstrate how http requests talk to web service


GET https://fakestoreapi.com/products

###

GET https://fakestoreapi.com/products/4

###

GET https://fakestoreapi.com/products/category/electronics

###

# User registration
POST https://fakestoreapi.com/users
Content-Type: application/json

{
    "username": "michael",
    "password": "michael123"
}

### 

# User info
GET https://fakestoreapi.com/users/

###

# User login
POST https://fakestoreapi.com/auth/login
Content-Type: application/json

{
    "username": "johnd",
    "password": "m38rmF$"
}



